language: c
before_script: ./bootstrap
install:
  - wget http://www.lwes.org/downloads/lwes-c/lwes-0.25.0.tar.gz
  - tar -xzvf lwes-0.25.0.tar.gz
  - cd lwes-0.25.0 && ./configure --disable-hardcore --prefix=$HOME && make install && cd ..
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/lib/pkgconfig
  - export CFLAGS=`pkg-config --cflags lwes-0`
  - export LIBS=`pkg-config --libs lwes-0`
